#include "BloodDrive.h"




void BloodDrive::create()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AC8 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AC8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodDrive::update()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ACA begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ACA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodDrive::deleteBloodDrive()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ACC begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ACC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodDrive::getBloodDriveList()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ACE begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ACE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
