#include "BloodType.h"




void BloodType::create()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AAB begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AAB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodType::deleteBlood()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AAD begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AAD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodType::getBloodByName(void  b)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AAF begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AAF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodType::update()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AB1 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AB1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BloodType::getBloodName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AB4 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AB4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
