#include "Donor.h"




void Donor::create()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A78 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A78 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Donor::update()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A7A begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Donor::delete()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A7C begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A7C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Donor::getAllDonors()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A7E begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A7E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Donor::getDonor(void  id)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A80 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000A80 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
