#include "Meeting.h"




void Meeting::create()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AD4 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AD4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Meeting::update()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ADC begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ADC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Meeting::deleteMeeting()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ADE begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000ADE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Meeting::getDonationsByBloodDrive(void  id)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AE0 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AE0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Meeting::getDonationsByDonor(void  id)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AE3 begin
{
}
// section 127-0-1-1--32cefa1:149bf256bc4:-8000:0000000000000AE3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
